config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/account' => 'accounts#show', as: :user_account_root

  resources 'accounts', only: [] do
    resource 'payments', only: %i[new create]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: redirect('/account')
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/money_transaction.rb
# frozen_string_literal: true

class MoneyTransaction < ApplicationRecord
end

app/models/money_transaction_item.rb
# frozen_string_literal: true

class MoneyTransactionItem < ApplicationRecord
  belongs_to :money_transaction
  belongs_to :account
  belongs_to :next_account_item,
             class_name: 'MoneyTransactionItem',
             optional: true

  monetize :amount_cents, with_currency: :seu
  monetize :account_balance_cents, with_currency: :seu
end

app/models/payment.rb
# frozen_string_literal: true

class Payment
  include ActiveModel::Model

  attr_accessor :from_account_id, :to_account_reference, :amount, :description

  validates :from_account_id, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :to_account_reference, presence: true
  validate :to_account_reference_must_be_a_valid_account_reference

  def save
    return false unless valid?

    create_money_transaction
  end

  private

  def to_account_reference_must_be_a_valid_account_reference
    return if to_account

    errors.add(:to_account_reference, 'must be a valid account reference')
  end

  def to_account
    Account.find_by(reference: to_account_reference)
  end

  def create_money_transaction
    MoneyTransactionCreationService.call(
      description:,
      money_transaction_items_attributes: [
        { account_id: from_account_id, amount: -amount.to_money(:seu) },
        { account_id: to_account.id, amount: amount.to_money(:seu) }
      ]
    )
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :account, dependent: :destroy
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :ensure_user_account_is_setup

  def show
    @account = account
    @money_transaction_items = MoneyTransactionItem
                               .where(account: @account)
                               .joins(:money_transaction)
                               .eager_load(:money_transaction)
                               .order(id: :desc)
                               .page params[:page]

    flash.now[:notice] = I18n.t('new_sign_up_award') if new_user?
  end

  private

  def account
    existing_user_account || new_account
  end

  def new_user?
    existing_user_account.blank?
  end

  def existing_user_account
    return @existing_user_account if defined?(@existing_user_account)

    @existing_user_account = Account.find_by(user: current_user)
  end

  def ensure_user_account_is_setup
    return unless new_user?

    MoneyTransactionCreationService.call(
      description: 'New signup award',
      money_transaction_items_attributes: [
        { account_id: system_account.id, amount: -award_amount.to_money(:seu) },
        { account_id: new_account.id, amount: award_amount.to_money(:seu) }
      ]
    )
  end

  def system_account
    Account.where(user: nil).sole
  end

  def new_account
    @new_account ||= Account.create(user: current_user)
  end

  def award_amount
    100.to_money(:seu)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protected

  def after_sign_in_path_for(_resource)
    user_account_root_path
  end

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  before_action :authorize_user_access_to_from_account!

  def new
    @payment = new_payment
  end

  def create
    @payment = build_payment

    if @payment.save
      redirect_to user_account_root_path,
                  notice: I18n.t('payment_successful')
    else
      render 'new'
    end
  end

  private

  def new_payment
    Payment.new(from_account_id: params[:account_id])
  end

  def build_payment
    Payment.new(
      from_account_id: params[:account_id],
      to_account_reference: payment_params[:to_account_reference],
      amount: payment_params[:amount],
      description: payment_params[:description]
    )
  end

  def payment_params
    params.require(:payment).permit(
      :to_account_reference,
      :description,
      :amount
    )
  end

  def from_account
    @from_account ||= Account.find(params[:account_id])
  end

  def authorize_user_access_to_from_account!
    return if from_account.user_id == current_user.id

    head :forbidden
  end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
  def account_balance(money_transaction_item)
    return 0.to_money(:seu).format unless money_transaction_item

    money_transaction_item.account_balance.format
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/accounts/_account_transactions.html.erb
<figure>
  <table>
    <caption>
      <h2>Transactions</h2>
    </caption>

    <thead>
      <tr>
        <th>Time</th>
        <th>Ref</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Balance</th>
      </tr>
    </thead>

    <% money_transaction_items.each do |item| %>
      <%- transaction = item.money_transaction %>

      <tr>
        <td><%= time_ago_in_words(transaction.created_at) %> ago</td>
        <td><%= transaction.reference %></td>
        <td><%= transaction.description %></td>
        <td><%= item.amount.format %></td>
        <td><%= item.account_balance.format %></td>
      </tr>
    <% end %>

  </table>

  <%= paginate money_transaction_items %>
</figure>

app/views/accounts/show.html.erb
<h1>Account</h1>

<table>
  <tr>
    <th>Account Reference</th>
    <td><%= @account.reference %></td>
  </tr>
  <tr>
    <th>Account Balance</th>
    <td><%= account_balance(@money_transaction_items.first) %></td>
  </tr>
</table>

<%= link_to 'Make a Payment', new_account_payments_path(@account) %>

<%= render partial: 'account_transactions',
           locals: { money_transaction_items: @money_transaction_items } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatBank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="notice">
        <%= msg %>
      </div>
    <% end %>

    <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } if current_user %>

    <%= yield %>
  </body>
</html>

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= simple_form_for(@payment,
                    as: :payment,
                    method: :post,
                    url: account_payments_path(@payment.from_account_id)) do |f| %>
  <%= f.input :description %>
  <%= f.input :to_account_reference %>
  <%= f.input :amount %>
  <%= f.submit 'Create payment' %>
<% end %>